### ISSUE TITLE
Already working?

### ISSUE THREAD

**Issue by esilvajr** [LogansUA/blizzard-api-php-client#17]
Code: 

$client = new BlizzardApi\BlizzardClient('My_API_KEY');

$blizzApi = new BlizzardApi\Service\Diablo($client);
$blizzApi->getCareerProfile('MY_BATTLE_TAG'');

Expected: 

Json with career data.

Got:

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://us.api.battle.net/d3/profile/MY_BATTLE_TAG?locale=en_us&apiKey=My_API_KEY/` resulted in a `404 Not Found`...

**Comment by illepic** [comment]
Is `https://us.api.battle.net/d3/profile/MY_BATTLE_TAG?locale=en_us&apiKey=My_API_KEY/` the actual URL that was reported, or are you using this to anonymize your example?

If that's the actual output, you'll need to change `MY_BATTLE_TAG` and `MY_API_KEY` to real values.

**Comment by esilvajr** [comment]
It's just for anonymize. I can put the full URL and configs if you need it.

**Comment by illepic** [comment]
Gotcha, sorry about that. I've only worked with the WoW side of this API, haven't yet tried the Diablo side.

**Comment by esilvajr** [comment]
I got the error:
The error was happening because of the 'battleTag' format. I was sending in the format 'name#number' and the acceptable one is 'name-number'.

Ty for the help @illepic.
