### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by RM29** [LogansUA/blizzard-api-php-client#25]
Seems to be a good work, but not everybody have access to his server.
Like me i think lots of people cant use your work because of that.
Personnaly i only have access to ftp & mysql.

**Comment by LogansUA** [comment]
@Ronanzzzzzzzzzz Hello. What do you mean by `access to his server`? To blizzard server? [There's](https://dev.battle.net/) all information about how to getting started with the Blizzard dev API.

**Comment by RM29** [comment]
i dont get how you instal your api without having to run cmd on server

**Comment by LogansUA** [comment]
You can download this library as ZIP archive and then put it on test server via FTP.

**Comment by RM29** [comment]
oh ok, its just the composer thing that i belived was necessary since it was the exemple.

**Comment by LogansUA** [comment]
Well, composer is necessary there for other dependencies (which listed in composer.json) but you can download them too.
Initially this package is designed with using composer.

You can create local project, install dependencies with this package via composer and then move whole `vendor` directory to you'r server via FTP, and then use them. I guess it will be the best solution in your situation

**Comment by RM29** [comment]
Ok thx for your help !

**Comment by LogansUA** [comment]
Np, good luck with that. But generally i suggest you to get ssh access and use the composer :)
